name: Android Release

on:
  push:
    branches:
      - balazskiss/android-builds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world
        run: |
          chmod +x ./scripts/package_android.sh
          ./scripts/package_android.sh