name: Android Release

on:
  push:
    branches:
      - balazskiss/android-builds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK and CMake
        run: |
          sdkmanager --install "ndk;24.0.8215888"
          sdkmanager --install "cmake;3.10.2.4988404"
          echo "Installed NDK and CMake."

      - name: Install Backtrace Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libbacktrace-dev
          echo "Installed libbacktrace-dev."

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables."
          echo "ANDROID_SDK_ROOT is set to $ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_HOME is set to $ANDROID_NDK_HOME"
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/24.0.8215888" >> $GITHUB_ENV
          echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/24.0.8215888" >> $GITHUB_ENV
          echo "PATH=$ANDROID_SDK_ROOT/ndk/24.0.8215888:$PATH" >> $GITHUB_ENV

      - name: Build Android Libs
        run: |
          echo "ANDROID_NDK is set to $ANDROID_NDK"
          chmod +x ./scripts/package_android.sh
          ./scripts/package_android.sh